version: '2'

services:
  mariadb:
    image: 'mariadb:10.2'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userManagement

volumes:
  mariadb_data:
    driver: local